import * as THREE from 'three';
import './style.css';

const saveKey='sum-greatness-save-v1';
const defaultState={cash:2500,gems:25,energy:100,xp:120,level:1,reputation:5,mode:'walk',missionStep:0,businesses:[],properties:[],vehicles:['Metro Pass'],lessons:[],playerName:'Founder',avatar:{style:'Executive',outfit:'Midnight Gold',skin:'#7b4b34'},district:'Gaslamp Quarter'};
const state={...defaultState,...JSON.parse(localStorage.getItem(saveKey)||'{}')};
const $=s=>document.querySelector(s);
const persist=()=>localStorage.setItem(saveKey,JSON.stringify(state));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
function sync(){ $('#cash').textContent=state.cash.toLocaleString();$('#gems').textContent=state.gems;$('#energy').textContent=state.energy;$('#level').textContent=`LEVEL ${state.level} · ${state.level<3?'ROOKIE':'ENTREPRENEUR'}`;$('#xp-fill').style.width=`${state.xp%100}%`;$('#mode-btn').textContent=state.mode==='walk'?'DRIVE':'WALK';persist() }

const renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x7aa1bd);scene.fog=new THREE.Fog(0x9bb2bd,28,110);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,250);camera.position.set(10,11,15);
scene.add(new THREE.HemisphereLight(0xffd9a3,0x1f2b23,2.4));const sun=new THREE.DirectionalLight(0xffc77a,3);sun.position.set(-20,28,12);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x415b39,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const roadMat=new THREE.MeshStandardMaterial({color:0x24272b,roughness:.85});
for(let i=-60;i<=60;i+=30){const road=new THREE.Mesh(new THREE.PlaneGeometry(12,170),roadMat);road.rotation.x=-Math.PI/2;road.position.set(i,.015,0);scene.add(road);const cross=road.clone();cross.rotation.z=Math.PI/2;cross.position.set(0,.02,i);scene.add(cross)}
const goldMat=new THREE.MeshStandardMaterial({color:0xd5a840,metalness:.7,roughness:.25});
for(let x=-52;x<=52;x+=15)for(let z=-52;z<=52;z+=15){if(Math.abs(x%30)<7||Math.abs(z%30)<7)continue;const h=THREE.MathUtils.randFloat(6,22);const colors=[0x665947,0x31495a,0x6c5148,0x4b545a];const b=new THREE.Mesh(new THREE.BoxGeometry(9,h,9),new THREE.MeshStandardMaterial({color:colors[Math.floor(Math.random()*colors.length)],roughness:.72}));b.position.set(x,h/2,z);b.castShadow=true;b.receiveShadow=true;scene.add(b);for(let y=2;y<h-1;y+=3){const band=new THREE.Mesh(new THREE.BoxGeometry(9.05,.35,9.05),goldMat);band.position.set(x,y,z);scene.add(band)}}
function makePerson(color=0x151515,skin=0x7b4b34){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.25,5,10),new THREE.MeshStandardMaterial({color,roughness:.55}));body.position.y=1.25;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),new THREE.MeshStandardMaterial({color:skin}));head.position.y=2.55;head.castShadow=true;g.add(head);g.userData={body,head};return g}
const player=makePerson(0x13110f);player.position.set(0,0,8);scene.add(player);const crown=new THREE.Mesh(new THREE.ConeGeometry(.36,.45,5),goldMat);crown.position.y=3.15;player.add(crown);
const npc=makePerson(0x8b2f56);npc.position.set(8,0,-3);scene.add(npc);const marker=new THREE.Mesh(new THREE.TorusGeometry(1.2,.14,10,32),goldMat);marker.rotation.x=Math.PI/2;marker.position.set(8,.15,-3);scene.add(marker);
const car=new THREE.Group();const chassis=new THREE.Mesh(new THREE.BoxGeometry(2.2,.7,4.2),new THREE.MeshStandardMaterial({color:0x0c0c0d,metalness:.8,roughness:.2}));chassis.position.y=.75;car.add(chassis);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.8,.65,2),new THREE.MeshStandardMaterial({color:0xd7aa42,metalness:.55}));cabin.position.set(0,1.3,.2);car.add(cabin);car.visible=false;scene.add(car);
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let joy={x:0,y:0};const joystick=$('#joystick'),knob=joystick.querySelector('i');function setJoy(e){const p=e.touches?.[0]||e,r=joystick.getBoundingClientRect(),dx=p.clientX-(r.left+r.width/2),dy=p.clientY-(r.top+r.height/2),d=Math.min(32,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);joy={x:Math.cos(a)*d/32,y:Math.sin(a)*d/32};knob.style.transform=`translate(${joy.x*28}px,${joy.y*28}px)`}joystick.addEventListener('pointerdown',e=>{joystick.setPointerCapture(e.pointerId);setJoy(e)});joystick.addEventListener('pointermove',e=>{if(joystick.hasPointerCapture(e.pointerId))setJoy(e)});joystick.addEventListener('pointerup',()=>{joy={x:0,y:0};knob.style.transform='' });
function districtFor(x,z){if(z<-30)return'La Jolla Coast';if(z>30)return'Chula Vista Market';if(x<-30)return'Barrio Logan Arts';if(x>30)return'Mission Valley';return'Gaslamp Quarter'}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),speed=state.mode==='drive'?10:5;const dx=(keys.d?1:0)-(keys.a?1:0)+joy.x,dz=(keys.s?1:0)-(keys.w?1:0)+joy.y;if(Math.abs(dx)+Math.abs(dz)>.05){const v=new THREE.Vector3(dx,0,dz).normalize();player.position.addScaledVector(v,speed*dt);player.rotation.y=Math.atan2(v.x,v.z);player.position.x=THREE.MathUtils.clamp(player.position.x,-72,72);player.position.z=THREE.MathUtils.clamp(player.position.z,-72,72);const next=districtFor(player.position.x,player.position.z);if(next!==state.district){state.district=next;$('#district').textContent=next;toast(`Now entering ${next}`);persist()}}car.visible=state.mode==='drive';player.visible=state.mode==='walk';car.position.copy(player.position);car.rotation.copy(player.rotation);marker.rotation.z+=dt*.7;marker.position.y=.2+Math.sin(performance.now()/400)*.12;npc.position.x=8+Math.sin(performance.now()/2400)*2;const target=player.position.clone().add(new THREE.Vector3(8,8,12));camera.position.lerp(target,.055);camera.lookAt(player.position.x,1.2,player.position.z);renderer.render(scene,camera)}

const panels={
 empire:()=>`<button class="close">×</button><h2>Your Empire</h2><p>Start small. Build smart. Own the city.</p><div class="grid"><div class="card"><em>👕</em><strong>Streetwear Studio</strong><small>Startup cost: $2,000</small><span>Potential: $450/day</span><button data-buy="business">LAUNCH</button></div><div class="card locked"><em>🏠</em><strong>First Rental</strong><small>Unlock at Level 3</small></div><div class="card locked"><em>🏢</em><strong>Downtown Headquarters</strong><small>Unlock at Level 8</small></div></div>`,
 missions:()=>`<button class="close">×</button><h2>Missions</h2><div class="grid"><div class="card"><em>🎯</em><strong>Make Your First Move</strong><small>Talk to Maya · 0/1</small><span>$750 + 100 XP</span></div><div class="card"><em>💼</em><strong>First Customer</strong><small>Launch a business</small><span>$1,200 + Reputation</span></div></div>`,
 learn:()=>`<button class="close">×</button><h2>Greatness Academy</h2><p>Turn game decisions into real-world business skills.</p><div class="grid"><div class="card"><em>💡</em><strong>Validate the Idea</strong><small>Talk to customers before spending big.</small><button data-lesson="validation">START</button></div><div class="card"><em>📊</em><strong>Know Your Numbers</strong><small>Revenue is not the same as profit.</small><button data-lesson="numbers">START</button></div><div class="card"><em>♻️</em><strong>Build to Last</strong><small>Balance people, profit, and resources.</small><button data-lesson="sustainability">START</button></div></div>`,
 profile:()=>`<button class="close">×</button><h2>${state.playerName}</h2><p>Level ${state.level} entrepreneur · ${state.reputation} reputation</p><div class="grid"><div class="card"><strong>${state.businesses.length}</strong><small>Businesses</small></div><div class="card"><strong>${state.properties.length}</strong><small>Properties</small></div><div class="card"><strong>${state.vehicles.length}</strong><small>Vehicles</small></div><div class="card"><strong>${state.lessons.length}/3</strong><small>Lessons</small></div></div><h3>Character Studio</h3><div class="grid"><div class="card"><em>🕴🏾</em><strong>Executive</strong><small>Tailored business silhouette</small><button data-avatar="Executive">SELECT</button></div><div class="card"><em>🧢</em><strong>Street Founder</strong><small>Premium urban streetwear</small><button data-avatar="Street Founder">SELECT</button></div><div class="card"><em>👩🏾‍💼</em><strong>Boss</strong><small>Modern luxury leadership</small><button data-avatar="Boss">SELECT</button></div></div><h3>Wardrobe</h3><div class="choice"><button data-outfit="Midnight Gold">Midnight Gold</button><button data-outfit="Royal Burgundy">Royal Burgundy</button><button data-outfit="Ocean Blue">Ocean Blue</button></div><h3>Optional Store</h3><p>Cosmetics, VIP rewards, and convenience items will use RevenueCat. Progress remains available without purchases. Rewarded AdMob placements are optional.</p>`,
 world:()=>''};
function openPanel(name){const p=$('#panel');if(name==='world'){p.classList.remove('open');return}p.innerHTML=panels[name]();p.classList.add('open');p.querySelector('.close').onclick=()=>p.classList.remove('open')}
document.addEventListener('click',e=>{const panel=e.target.closest('[data-panel]')?.dataset.panel;if(panel)openPanel(panel);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='mode'){state.mode=state.mode==='walk'?'drive':'walk';toast(`${state.mode==='walk'?'Walking':'Driving'} mode`);sync()}if(action==='interact'){const dist=player.position.distanceTo(npc.position);if(dist<6){openConversation()}else toast('Move closer to Maya at the gold marker.')}if(action==='focus-mission'){player.position.set(3,0,1);toast('Mission marker is ahead.')}const avatar=e.target.closest('[data-avatar]')?.dataset.avatar;if(avatar){state.avatar.style=avatar;toast(`${avatar} character selected`);sync();openPanel('profile')}const outfit=e.target.closest('[data-outfit]')?.dataset.outfit;if(outfit){state.avatar.outfit=outfit;const colors={'Midnight Gold':0x13110f,'Royal Burgundy':0x661f36,'Ocean Blue':0x173f65};player.userData.body.material.color.setHex(colors[outfit]);toast(`${outfit} equipped`);sync()}const buy=e.target.closest('[data-buy]');if(buy){if(state.businesses.includes('Streetwear Studio'))return toast('You already own this business.');if(state.cash<2000)return toast('You need more cash.');state.cash-=2000;state.businesses.push('Streetwear Studio');state.xp+=100;state.reputation+=5;toast('Streetwear Studio launched!');sync();openPanel('empire')}const lesson=e.target.closest('[data-lesson]')?.dataset.lesson;if(lesson){if(!state.lessons.includes(lesson)){state.lessons.push(lesson);state.xp+=25;toast('+25 XP · Lesson completed');sync()}openPanel('learn')}});
function openConversation(){const p=$('#panel');p.innerHTML=`<h2>Maya · Local Business Mentor</h2><p>“Great businesses solve a real problem. Before spending your money, what should you do first?”</p><div class="choice"><button data-answer="correct">Talk to possible customers and test the idea</button><button data-answer="wrong">Spend everything on inventory immediately</button><button data-answer="wrong">Copy a business without researching it</button></div>`;p.classList.add('open');p.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer==='correct'){state.cash+=750;state.xp+=100;state.reputation+=3;state.missionStep=1;toast('Mission complete · $750 + 100 XP');$('#mission-card').innerHTML='<small>MISSION COMPLETE</small><strong>Make Your First Move</strong><p>You learned to validate an idea before investing.</p>';sync();p.classList.remove('open')}else toast('Think like an owner: research before spending.')})}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setSize(innerWidth,innerHeight);$('#district').textContent=state.district;sync();animate();
